import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='light'>
			<body
				className={cn(
					'min-h-screen font-sans antialiased grainy pt-20',
					inter.className
				)}
			>
				<header className='fixed  w-full top-0 bg-slate-50 z-[9999]'>
					<Navbar />
				</header>
				{children}
			</body>
		</html>
	);
}
